name: cakes_calculator
description: "Cakes calculator"

publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: Italian
     fonts:
       - asset: assets/fonts/Italianno-Regular.ttf


